name: Build and deploy - iris-gestao-apidev (develop)

on:
  push:
    branches:
      - develop
    paths:
      - IrisGestao/IrisApi/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build IrisGestao/IrisApi/IrisWebApi --configuration Release

      - name: dotnet publish
        run: dotnet publish IrisGestao/IrisApi/IrisWebApi -c Release --no-build -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp
          retention-days: 5

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'irisgestao-devapi'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEB_API_DEV }}
          package: .
